on:
  workflow_call:

jobs:
  audit:
    runs-on: [self-hosted, gke]
    steps:

    - id: 'gh-app'
      name: 'Get Token'
      uses: 'tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92' #v1.7.0
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_PRIVATE_KEY }}

    - name: 'Checkout repo'
      uses: 'actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3' #v3.1.0

    - name: 'Setup creds'
      run: |
        git config --global url."https://x-access-token:${{ steps.gh-app.outputs.token }}@github.com".insteadOf "ssh://git@github.com"

    - name: 'Audit check'
      uses: 'actions-rs/audit-check@35b7b53b1e25b55642157ac01b4adceb5b9ebef3'
      with:
        token: ${{ steps.gh-app.outputs.token }}
