on:
  workflow_call:
    inputs:
      environment:
        description: 'To describe a general deployment target'
        required: true
        type: string
      path:
        description: |-
          The path to a file or folder inside the action's filesystem
          that should be uploaded to the bucket.
          You can specify either the absolute path or the relative path from the action.
        required: true
        type: string
      destination:
        description: |-
          GCS bucket name of form <bucketname> or with an optional prefix
          of form <bucketname>/<prefix>
        required: true
        type: string

jobs:
  upload-cloud-storage:

    runs-on: [self-hosted, gke]

    environment:
      name: ${{ inputs.environment }}

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.3.0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' #v1.0.0
        with:
          workload_identity_provider: ${{ secrets.GH_ACTIONS_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_SA_DATA }}

      - id: 'upload-folder'
        name: 'Upload folder'
        uses: 'google-github-actions/upload-cloud-storage@a5b77a3bf84da1791719585d327e5f90ae5cb53c' #v1.0.0
        with:
          path: '${{ inputs.path }}'
          destination: '${{ inputs.destination }}'
          gzip: false
