name: Build and push Docker images

on: workflow_call

jobs:
  dockerize:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2
