on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
      docker_context:
        required: false
        type: string
        default: '.'
      docker_build_args:
        required: false
        type: string

jobs:
  build:
    runs-on: [self-hosted, dockerize]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout Repo'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0

      - id: 'meta'
        name: 'Docker Meta'
        uses: 'docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96' #v4.1.1
        with:
          images: ${{ inputs.image_repository }}
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,suffix=-{{sha}},event=pr
            type=ref,suffix=-{{sha}},event=tag
            type=semver,event=tag,pattern={{raw}}

      # Enable Registry Cache
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98' #v2.2.1

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' #v0.8.3
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GH_ACTIONS_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_SA_GCR }}

      - name: 'Login to GCR'
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' #v2.1.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Login to GAR'
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' #v2.1.0
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Build and Push'
        uses: 'docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671' #v3.2.0
        with:
          context: ${{ inputs.docker_context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # cache-from: type=registry,ref=${{ inputs.image_repository }}:buildcache
          # cache-to: type=registry,ref=${{ inputs.image_repository }}:buildcache,mode=max
          build-args: ${{ inputs.docker_build_args }}
          secrets: |
            "npm_token=${{ secrets.NPM_AUTH_TOKEN }}"
