on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
      checkout_repository:
        required: false
        type: string
      checkout_submodules:
        required: false
        type: string
      build_context:
        required: false
        type: string
        default: '.'
      buildx_version:
        required: false
        type: string
        default: 'v0.10.0'
      docker_push:
        required: false
        type: boolean
        default: true
      latest_tag:
        required: false
        type: string

jobs:
  build:
    runs-on: [self-hosted, dockerize]

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: 'gh-app'
        name: 'Get Token'
        uses: 'tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92' #v1.7.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: 'Checkout Repo With Submodule'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0
        with:
          repository: ${{ inputs.checkout_repository }}
          token: ${{ steps.gh-app.outputs.token }}
          submodules: ${{ inputs.checkout_submodules }}

      - id: 'meta'
        name: 'Docker Meta'
        uses: 'docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96' #v4.1.1
        env:
          DOCKER_METADATA_PR_HEAD_SHA: true
        with:
          images: ${{ inputs.image_repository }}
          tags: |
            type=ref,suffix=-{{sha}},event=branch
            type=ref,suffix=-{{sha}},event=pr
            type=ref,suffix=-{{sha}},event=tag
            type=semver,event=tag,pattern={{raw}}
            type=raw,value=${{ (inputs.latest_tag != '' && 'latest' ) }},enable=${{ inputs.latest_tag != '' }}

      # Enable Registry Cache
      - name: 'Set up Docker Buildx'
        uses: 'docker/setup-buildx-action@f03ac48505955848960e80bbb68046aa35c7b9e7' #v2.2.1
        with:
          version: ${{ inputs.buildx_version }}

      - id: 'auth'
        if: ${{ inputs.docker_push }}
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d' #v0.8.3
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GH_ACTIONS_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_SA_GCR }}

      - name: 'Login to GCR'
        if: ${{ inputs.docker_push }}
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' #v2.1.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Login to GAR'
        if: ${{ inputs.docker_push }}
        uses: 'docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a' #v2.1.0
        with:
          registry: us-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Build and Push'
        uses: 'docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671' #v3.2.0
        with:
          context: ${{ inputs.build_context }}
          file: ${{ inputs.dockerfile_path }}
          push: ${{ inputs.docker_push }}
          tags: ${{ steps.meta.outputs.tags }}
          # cache-from: type=registry,ref=${{ inputs.image_repository }}:buildcache
          # cache-to: type=registry,ref=${{ inputs.image_repository }}:buildcache,mode=max
          secrets: |
            "github_token=${{ steps.gh-app.outputs.token }}"
