on:
  workflow_call:
    inputs:
      image_repository:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: 'Dockerfile'
      workload_identity_provider:
        required: true
        type: string
      service_account:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b #v3.0.2

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@dac4e13deb3640f22e3ffe758fd3f95e6e89f712 # v0.8.1
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ inputs.workload_identity_provider }}
          service_account: ${{ inputs.service_account }}

      - name: 'Login to GCR'
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b #v2.0.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: 'Build and Push'
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 #v3.1.1
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ inputs.image_repository }}:${{ inputs.image_tag }}
          cache-from: type=registry,ref=${{ inputs.image_repository }}/cache
          cache-to: type=registry,ref=${{ inputs.image_repository }}/cache,mode=max
