on:
  workflow_call:
    inputs:
      go_version:
        description: "The Go version to download (if necessary) and use."
        required: true
        type: string
      go_check_latest:
        description: "The action first checks if the cached version is the latest one."
        required: false
        type: string
      go_cache:
        description: "Caching and restoring go modules and build outputs."
        required: false
        type: string
      working_directory:
        description: 'directory path'
        required: false
        type: string
        default: "."

jobs:
  golang:
    runs-on: [self-hosted, gke]

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]

    steps:
      - id: "gh-app"
        name: "Get Token"
        uses: "tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92" #v1.7.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: "Checkout Repo"
        uses: "actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3" #v3.1.0

      - name: "Setup Go"
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 #v3.3.0
        with:
          go-version: "${{ inputs.go_version }}"
          check-latest: "${{ inputs.go_check_latest }}"
          cache: "${{ inputs.go_cache }}"

      - name: "Get Repository Name"
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: "Go Build"
        run: |
          git config --global url."https://x-access-token:${{ steps.gh-app.outputs.token }}@github.com".insteadOf "https://github.com"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ env.REPOSITORY_NAME }}-${{ matrix.goos }}_${{ matrix.goarch }}
          sha256sum ${{ env.REPOSITORY_NAME }}-${{ matrix.goos }}_${{ matrix.goarch }} > ${{ env.REPOSITORY_NAME }}-${{ matrix.goos }}_${{ matrix.goarch }}.sha256sum.txt
        working-directory: "${{ inputs.working_directory }}"

      - name: "Release"
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 #v0.1.15
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ inputs.working_directory }}/${{ env.REPOSITORY_NAME }}-${{ matrix.goos }}_${{ matrix.goarch }}
            ${{ inputs.working_directory }}/${{ env.REPOSITORY_NAME }}-${{ matrix.goos }}_${{ matrix.goarch }}.sha256sum.txt
