on:
  workflow_call:
    inputs:
      node_version:
        description: 'The Node version to download (if necessary) and use.'
        required: false
        type: string
        default: 'latest'
      node_options:
        description: 'node options'
        required: false
        type: string
      node_script:
        description: 'Script to execute'
        required: false
        type: string
      timeout_minutes:
        description: 'Set timeout for this action'
        required: false
        type: number
        default: 360
      node_arguments:
        description: 'node arguments'
        required: false
        type: string

jobs:
  nodejs:
    runs-on: [self-hosted, stress-test]
    timeout-minutes: ${{ inputs.timeout_minutes }}
    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.0.3

      - name: 'Setup Node'
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c #v3.4.1
        with:
          node-version: '${{ inputs.node_version }}'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run with Node'
        run: ${{ inputs.node_options }} node ${{ inputs.node_script }} ${{ inputs.node_arguments }}
