on:
  workflow_call:
    inputs:
      java_version:
        description: 'The Java version to set up. Takes a whole or semver Java version.'
        required: false
        type: string
        default: '18'
      maven_version:
        description: 'The Maven version to set up.'
        required: false
        type: string
        default: '3.8.6'
      checkout_repository:
        description: 'Repository name with owner.'
        required: false
        type: string
      java_distribution:
        description: 'Java distribution: temurin, zulu, microsoft, corretto'
        required: false
        type: string
        default: 'temurin'
      mvn_options:
        description: 'usage: mvn [options] [<goal(s)>] [<phase(s)>]'
        required: false
        type: string
      timeout_minutes:
        description: 'The maximum number of minutes to run the step before killing the process.'
        required: false
        type: number
        default: 60

jobs:
  java:

    runs-on: [self-hosted, stress-test]
    timeout-minutes: ${{ inputs.timeout_minutes }}

    steps:
      - id: 'gh-app'
        name: 'Get Token'
        uses: 'tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92' #v1.7.0
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: 'Checkout Repo'
        uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0
        with:
          repository: ${{ inputs.checkout_repository }}
          token: ${{ steps.gh-app.outputs.token }}

      - name: 'Cache local Maven repository'
        uses: 'actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0' #v3.0.11
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: 'Set up JDK'
        uses: 'actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98'
        with:
          distribution: '${{ inputs.java_distribution }}'
          java-version: '${{ inputs.java_version }}'

      - name: 'Set up Maven'
        uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f #v4.5
        with:
          maven-version: '${{ inputs.maven_version }}'

      - name: 'Build with Maven'
        run: mvn clean verify ${{ inputs.mvn_options }} -Denvironment=${{ inputs.environment }}
        continue-on-error: true

      - name: Tar files
        run: tar -cvf report-${{ inputs.environment }}.tar report

      - name: 'Upload Artifact'
        uses: 'actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce' #v3.1.0
        with:
          name: report-${{ inputs.environment }}
          path: report-${{ inputs.environment }}.tar
          retention-days: 10
