on:
  workflow_call:
    inputs:
      semgrep_options:
        required: false
        type: string
        default: '--config auto --exclude Dockerfile'

jobs:
  semgrep:
    runs-on: [self-hosted, gke]

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.0.2

      - name: 'Static analysis'
        run: semgrep ci ${{ inputs.semgrep_options }}

  TruffleHog:
    runs-on: [self-hosted, gke]

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c #v3.0.2
        with:
          fetch-depth: 0

      - name: 'TruffleHog OSS'
        uses: trufflesecurity/trufflehog@0c66d30c1f4075cee1aada2e1ab46dabb1b0071a #v3.12.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
