on:
  workflow_call:
    inputs:
      semgrep_options:
        required: false
        type: string
        default: '--config auto --exclude Dockerfile'

jobs:
  semgrep:
    runs-on: [self-hosted, gke]

    container:
      # A Docker image with Semgrep installed. Do not change this.
      image: returntocorp/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:

      - name: 'Checkout Repo'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.0.3

      - name: 'Static analysis'
        run: semgrep ci ${{ inputs.semgrep_options }}

  TruffleHog:
    runs-on: [self-hosted, gke]

    steps:
      - name: 'Checkout Repo'
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 #v3.0.3
        with:
          fetch-depth: 0

      - name: 'TruffleHog OSS'
        uses: trufflesecurity/trufflehog@2b1c42ceb17595fd68e183e881d9b70d84e9d3c1 #v3.12.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
