on:
  workflow_call:
    inputs:
      toolchain_version:
        description: 'The Rust toolchain version (ex: stable, nightly, 1.65, etc)'
        required: false
        type: string
        default: 'stable'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - id: 'gh-app'
      name: 'Get Token'
      uses: 'tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92' #v1.7.0
      with:
        app_id: ${{ secrets.GH_APP_ID }}
        private_key: ${{ secrets.GH_PRIVATE_KEY }}
    - name: 'Checkout repo'
      uses: 'actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c' #v3.1.0
    - name: 'Setup creds'
      run: |
        git config --global url."https://x-access-token:${{ steps.gh-app.outputs.token }}@github.com".insteadOf "ssh://git@github.com"
    - name: 'Install Rust toolchains (rustfmt, and clippy)'
      uses: 'dtolnay/rust-toolchain@e12eda571dc9a5ee5d58eecf4738ec291c66f295'
      with:
        profile: minimal
        toolchain: ${{ inputs.toolchain_version }}
    - name: 'Run tests'
      run: cargo test --all-targets --all-features --verbose -- --nocapture
